version: "3"
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
      - mongo
  backend:
    build: ./backend
    env_file:
      - mongo.env
  mongo:
    image: mongo
    env_file:
      - mongo.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
