version: "3"
services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "4000:4000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=4000
      - VUE_APP_BACKEND_IP=http://localhost
      - VUE_APP_BACKEND_PORT=5000
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FRONTEND_PORT=4000
      - FRONTEND_IP=http://localhost
    volumes:
      - ./backend:/app:rw
      - /app/node_modules
